### ISSUE TITLE
Scopes appear to be all remote references

### ISSUE THREAD

**Issue by jricher** [KantaraInitiative/wg-uma#170] opened 2015-07-15 01:57 UTC
The language around scope definitions makes it appear that they're all supposed to be reference URLs that resolve to JSON documents, but the protocol works fine without that structure.

**Comment by gffletch** [comment] 2015-07-16 17:41
yes, remote references are not required. Remote references make the most sense (to me) when leveraging a shared scope taxonomy/model.

**Comment by xmlgrrl** [comment] 2015-07-20 03:16
Originally, scope descriptions were indeed exclusively designed to require URIs, but they were changed to allow plain strings as well. Justin, are you thinking of the code examples (which I'm pretty sure 100% use URIs), or also of natural-language passages?

**Comment by xmlgrrl** [comment] 2015-07-20 04:05
Hmm, I just found a reference in Core Sec 3.3.2 (https://docs.kantarainitiative.org/uma/rec-uma-core.html#rfc.section.3.3.2) to "one more more URIs of scopes", which is incorrect; it should be "...identifiers of scopes".

**Comment by mmachulak** [comment] 2015-07-20 21:22
Duplicate of https://github.com/xmlgrrl/UMA-Specifications/issues/147

**Comment by jricher** [comment] 2015-07-21 06:20
Not a duplicate, but it subsumes the issue in #147

**Comment by mmachulak** [comment] 2015-07-21 09:22
OK - covers what is already discussed in #147

**Comment by jricher** [comment] 2015-09-05 01:59
Both example scopes in §3.2.1 (core) are URIs

**Comment by jricher** [comment] 2015-09-06 17:46
Also in resource reg §2.2

**Closed** 2015-09-09 04:55 UTC
Labels: core, editorial, rsrc-reg, V1.0.1
